spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/stepscount?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8"
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      access-to-underlying-connection-allowed: true
      #active-connections: 500
      max-active: 100
      min-idle: 10
      max-wait: 60000
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 200
        wall:
          config:
            multi-statement-allow: true
      test-on-borrow: true
      #test-while-idle: true
      #test-on-return: true
      #max-wait-thread-count: 0
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # http://127.0.0.1:8080/druid/index.html
      filters: stat,wall,slf4j
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 127.0.0.1
    password:
    database: 0
    timeout: PT1M1S
    jedis:
      pool.max-active: 200
      pool.max-idle: 50
      pool.max-wait: PT-1S
      pool.min-idle: 10
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #uri: mongodb://localhost/test
      database: test
      #username: root

server:
  port: 130
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    max-connections: 900
    min-spare-threads: 100
    accesslog:
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b %T'
      enabled: true
      directory: ${user.dir}/logs
      prefix: access.${HOST:127.0.0.1}.${server.port:8080}

app:
  access: #2秒内最多能访问2000次
    max-count: 20000
    seconds: 5

